### ISSUE TITLE
inster occur error

### ISSUE THREAD

**Issue by adminSxs** [driftluo/InfluxDBClient-rs#50]
```rust
use influx_db_client::{
    Client, Point, Points, Value, Precision, point, points
};




fn main() {
    let mut client=Client::default().set_authentication("wizdata","whizhome_sg");
    let point = point!("log")
        .add_tag("level",Value::String(String::from("debug")))
        .add_field("value",Value::Integer(1));
    let points=points!(point);
    tokio::runtime::Runtime::new().unwrap().block_on(async move{
        client.write_points(points,Some(Precision::Seconds),None).await.unwrap();
    });

}
```

log
```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Communication("error sending request for url (http://localhost:8086/write?u=wizdata&p=whizhome_sg&db=test&precision=s): connection closed before message completed")', src\main.rs:21:73
stack backtrace:
   0: std::panicking::begin_panic_handler
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\std\src\panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\/library\core\src\option.rs:1221
   3: core::result::Result<tuple<>, influx_db_client::error::Error>::unwrap<tuple<>,influx_db_client::error::Error>
             at D:\software\rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\result.rs:973
   4: w_gui::main::{{closure}}
             at .\src\main.rs:21
   5: core::future::from_generator::{{impl}}::poll<generator-0>
             at D:\software\rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\future\mod.rs:79
   6: tokio::runtime::enter::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\enter.rs:160
   7: tokio::coop::with_budget::{{closure}}<core::task::poll::Poll<tuple<>>,closure-0>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\coop.rs:127
   8: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::try_with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<tuple<>>>
             at D:\software\rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:265
   9: std::thread::local::LocalKey<core::cell::Cell<tokio::coop::Budget>>::with<core::cell::Cell<tokio::coop::Budget>,closure-0,core::task::poll::Poll<tuple<>>>
             at D:\software\rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\std\src\thread\local.rs:241
  10: tokio::runtime::enter::Enter::block_on<core::future::from_generator::GenFuture<generator-0>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\enter.rs:160
  11: tokio::runtime::thread_pool::ThreadPool::block_on<core::future::from_generator::GenFuture<generator-0>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\thread_pool\mod.rs:82
  12: tokio::runtime::{{impl}}::block_on::{{closure}}<core::future::from_generator::GenFuture<generator-0>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\mod.rs:446
  13: tokio::runtime::context::enter<closure-0,tuple<>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\context.rs:72
  14: tokio::runtime::handle::Handle::enter<closure-0,tuple<>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\handle.rs:76
  15: tokio::runtime::Runtime::block_on<core::future::from_generator::GenFuture<generator-0>>
             at D:\software\cargo\registry\src\github.com-1ecc6299db9ec823\tokio-0.2.22\src\runtime\mod.rs:448
  16: w_gui::main
             at .\src\main.rs:20
  17: core::ops::function::FnOnce::call_once<fn(),tuple<>>
             at D:\software\rustup\toolchains\stable-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\ops\function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: process didn't exit successfully: `target\debug\w-gui.exe` (exit code: 101)
```

**Comment by driftluo** [comment]
```
Communication("error sending request for url (http://localhost:8086/write?u=wizdata&p=whizhome_sg&db=test&precision=s): connection closed before message completed")
```
Please pay attention to the error message. This is an HTTP communication error. The connection was accidentally disconnected. It is a network condition that needs to be processed.

**Comment by adminSxs** [comment]
> ```
> Communication("error sending request for url (http://localhost:8086/write?u=wizdata&p=whizhome_sg&db=test&precision=s): connection closed before message completed")
> ```
> 
> Please pay attention to the error message. This is an HTTP communication error. The connection was accidentally disconnected. It is a network condition that needs to be processed.

i use postman can access fluxdb-server ,but use rust cannot 
![image](https://user-images.githubusercontent.com/15902505/98436910-dc5e5200-2119-11eb-9dd5-cb9622f6b25e.png)

**Comment by adminSxs** [comment]
influxdb server version is 1.8.3

**Comment by driftluo** [comment]
I used influxdb docker to test, but can't reproduce your situation

run docker：
```
$ docker run -p 8086:8086 influxdb:latest

ts=2020-11-07T09:10:40.228697Z lvl=info msg="InfluxDB starting" log_id=0QKVOsP0000 version=1.8.3 branch=1.8 commit=563e6c3d1a7a2790763c
6289501095dbec19244e
```

run test:
```
cargo test -- create_and_delete_measurement
```

influxdb log:
```
[httpd] 172.17.0.1 - root [07/Nov/2020:09:11:49 +0000] "POST /query?db=test_create_and_delete_measurement&p=%5BREDACTED%5D&q=Create+database+%22test_create_and_delete_measurement%22&u=root HTTP/1.1" 200 33 "-" "-" 4479a7a4-20d9-11eb-8001-0242ac110002 3783
[httpd] 172.17.0.1 - root [07/Nov/2020:09:11:49 +0000] "POST /write?db=test_create_and_delete_measurement&p=%5BREDACTED%5D&precision=s&u=root HTTP/1.1" 204 0 "-" "-" 447a5dd3-20d9-11eb-8002-0242ac110002 53777
ts=2020-11-07T09:11:49.436010Z lvl=info msg="Executing query" log_id=0QKVOsP0000 service=query query="DROP MEASUREMENT temporary"
[httpd] 172.17.0.1 - root [07/Nov/2020:09:11:49 +0000] "POST /query?db=test_create_and_delete_measurement&p=%5BREDACTED%5D&q=Drop+measurement+%22temporary%22&u=root HTTP/1.1" 200 33 "-" "-" 4482f689-20d9-11eb-8003-0242ac110002 4907
ts=2020-11-07T09:11:49.443127Z lvl=info msg="Executing query" log_id=0QKVOsP0000 service=query query="DROP DATABASE test_create_and_delete_measurement"
[httpd] 172.17.0.1 - root [07/Nov/2020:09:11:49 +0000] "POST /query?db=test_create_and_delete_measurement&p=%5BREDACTED%5D&q=Drop+database+%22test_create_and_delete_measurement%22&u=root HTTP/1.1" 200 33 "-" "-" 44840aa3-20d9-11eb-8004-0242ac110002 6652
```

run test:
```
cargo test -- use_points
```

influxdb log:
```
[httpd] 172.17.0.1 - root [07/Nov/2020:09:17:11 +0000] "POST /query?db=test_use_points&p=%5BREDACTED%5D&q=Create+database+%22test_use_points%22&u=root HTTP/1.1" 200 33 "-" "-" 0435a552-20da-11eb-8005-0242ac110002 3297
[httpd] 172.17.0.1 - root [07/Nov/2020:09:17:11 +0000] "POST /write?db=test_use_points&p=%5BREDACTED%5D&precision=s&u=root HTTP/1.1" 204 0 "-" "-" 04364a2b-20da-11eb-8006-0242ac110002 41659
ts=2020-11-07T09:17:14.100390Z lvl=info msg="Executing query" log_id=0QKVOsP0000 service=query query="DROP MEASUREMENT test1"
[httpd] 172.17.0.1 - root [07/Nov/2020:09:17:14 +0000] "POST /query?db=test_use_points&p=%5BREDACTED%5D&q=Drop+measurement+%22test1%22&u=root HTTP/1.1" 200 33 "-" "-" 0606d0be-20da-11eb-8007-0242ac110002 15671
ts=2020-11-07T09:17:14.118937Z lvl=info msg="Executing query" log_id=0QKVOsP0000 service=query query="DROP MEASUREMENT test2"
[httpd] 172.17.0.1 - root [07/Nov/2020:09:17:14 +0000] "POST /query?db=test_use_points&p=%5BREDACTED%5D&q=Drop+measurement+%22test2%22&u=root HTTP/1.1" 200 33 "-" "-" 0609a61f-20da-11eb-8008-0242ac110002 7056
ts=2020-11-07T09:17:14.129836Z lvl=info msg="Executing query" log_id=0QKVOsP0000 service=query query="DROP DATABASE test_use_points"
[httpd] 172.17.0.1 - root [07/Nov/2020:09:17:14 +0000] "POST /query?db=test_use_points&p=%5BREDACTED%5D&q=Drop+database+%22test_use_points%22&u=root HTTP/1.1" 200 33 "-" "-" 060b4f72-20da-11eb-8009-0242ac110002 7441
```
